# tensor intro

In [1]:
import torch 
import numpy as np

In [2]:
# creating tensor
#1. directly from the data 
a = [[1,2,3],[3,4,5]]
a_tensor = torch.tensor(a)

In [3]:
#2. From a numpy array
np_array = np.array(a)
a_np = torch.from_numpy(np_array)

In [7]:
#3 from another tensor
a_ones = torch.ones_like(a_tensor) # this retains the properties of a
print("this is a ones tensor",a_ones)
a_rand = torch.rand_like(a_tensor,dtype = torch.float)# overides the initail int datatype
print("this is a random tensor",a_rand)

this is a ones tensor tensor([[1, 1, 1],
        [1, 1, 1]])
this is a random tensor tensor([[0.7649, 0.3820, 0.8107],
        [0.6353, 0.9511, 0.3196]])


In [8]:
shape = (2,3,4)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[[0.4659, 0.3526, 0.2570, 0.5158],
         [0.2458, 0.8133, 0.1595, 0.5600],
         [0.3577, 0.5411, 0.1838, 0.8380]],

        [[0.7755, 0.1488, 0.2098, 0.1868],
         [0.4174, 0.7444, 0.4500, 0.9876],
         [0.4256, 0.6154, 0.9582, 0.7788]]]) 

Ones Tensor: 
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) 

Zeros Tensor: 
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [9]:
# attributes of tensor
tensor = torch.rand(2,3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [11]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
else:
  print("gpu not available")

gpu not available


In [13]:
# performing operation on tensor similiar ot list
tensor = torch.ones(4, 4)
tensor[:,2:-1] = 0
print(tensor)

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


In [25]:
# performing concatination
tensor1 = torch.ones(4,4)
t1 = torch.cat([tensor, tensor, tensor1], dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [26]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor1)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor1}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [28]:
# this preforms matrix wise multiplication
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor1.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor1.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [29]:
# in place operators where _ suffix wil change a
print(tensor, "\n")
tensor.add_(5)
print(tensor)
# there use is discoraged because of immediate loss of history

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [30]:
# tensor on cpu and numpy can share memory location
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [32]:
# but a change in tensor will reflect a change in numpys
t.add_(4)
print(t)
print(n)

tensor([5., 5., 5., 5., 5.])
[5. 5. 5. 5. 5.]


In [37]:
# similiarly numpy array can be converted to tensor
b = np.ones((4,4))
t = torch.from_numpy(b)
# but changes in array will also affect changes in tensor and vice versa

In [38]:
np.add(b,1,out = b)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [39]:
print(b)
print(t)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], dtype=torch.float64)


In [40]:
t.add_(23)

tensor([[25., 25., 25., 25.],
        [25., 25., 25., 25.],
        [25., 25., 25., 25.],
        [25., 25., 25., 25.]], dtype=torch.float64)

In [41]:
print(b)
print(t)

[[25. 25. 25. 25.]
 [25. 25. 25. 25.]
 [25. 25. 25. 25.]
 [25. 25. 25. 25.]]
tensor([[25., 25., 25., 25.],
        [25., 25., 25., 25.],
        [25., 25., 25., 25.],
        [25., 25., 25., 25.]], dtype=torch.float64)


# intro to autograd